import './globals.css'
import {Poppins} from '@next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200','400', '700', '900']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body  className="bgGradient">{children}</body>
    </html>
  )
}
